table inet vpn_router_lab {
  set strict_target {
    type ipv4_addr
    flags interval
    elements = { 172.30.20.20 }
  }

  chain prerouting {
    type filter hook prerouting priority mangle; policy accept;
    iifname "awg0" ip daddr @strict_target meta l4proto tcp tproxy ip to :12345 meta mark set 8192 accept
  }
}
