services:
  vpn-router-dns:
    build:
      context: ./dnsmasq
    image: vpn-router-dns:0.4.0-pre-alpha
    container_name: ${VPN_ROUTER_DNS_SERVICE_NAME:-vpn-router-dns}
    network_mode: host
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${VPN_ROUTER_DNSMASQ_CONFIG:?Set VPN_ROUTER_DNSMASQ_CONFIG}:/etc/dnsmasq.conf:ro

  vpn-router:
    image: ghcr.io/sagernet/sing-box@sha256:da0e2331395c9025a85fa58892772b4cdbe5f2e530e93defeec3968175d06c6d
    container_name: ${VPN_ROUTER_SERVICE_NAME:-vpn-router}
    network_mode: host
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${VPN_ROUTER_SING_BOX_CONFIG:?Set VPN_ROUTER_SING_BOX_CONFIG}:/etc/sing-box/config.json:ro
    command: ["-C", "/etc/sing-box", "run"]
